name: "ESA2022"
output_dir: "docs"
navbar:
  title: "Workshop"
  left:
    - text: "Home"
      href: index.md
    - text: "Morning"
      href: morning.html
    - text: "Afternoon"
      href: afternoon.html
output:
  html_document:
    theme: jekyll-theme-midnight


theme: jekyll-theme-slate